name: Deploy Frontend to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL_PROD }}
          VITE_API_VERSION: v1
          VITE_API_TIMEOUT: 45000
          VITE_APP_NAME: Vulnera
          VITE_APP_VERSION: 1.0.0
          VITE_ENVIRONMENT: production
          VITE_ENABLE_DEBUG: false

      - name: Upload to Azure Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name vulnerastorageaccount \
              --auth-mode key \
              -s ./frontend/dist \
              -d '$web' \
              --overwrite true
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
