# .github/workflows/deploy-frontend.yml

name: Build and Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package*.json'
      - 'vite.config.*'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  NODE_VERSION: "20"
  VITE_APP_NAME: "Vulnera"
  VITE_APP_VERSION: "1.0.0"

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 3. Install dependencies
        run: npm install

      - name: 4. Build application
        # ❗️ تحذير: تم إزالة متغيرات البيئة من هنا.
        # سيقوم التطبيق الآن باستخدام القيم الافتراضية (مثل localhost)
        run: npm run build

      - name: 5. Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" 
          api_location: ""
          output_location: "dist"

      - name: 6. Add deployment summary
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment:** Production" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Frontend URL:** [${{ steps.deploy.outputs.static_web_app_url }}](${{ steps.deploy.outputs.static_web_app_url }})" >> $GITHUB_STEP_SUMMARY

